### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by putianyi889** [darknessgod/whitemeow#6]
- [] 动态摆雷 https://github.com/darknessgod/whitemeow/issues/4
- [] 大图滚屏 https://github.com/darknessgod/whitemeow/issues/3
- [] 拖动连击 https://github.com/darknessgod/whitemeow/issues/5
